import type { FeatureManifest } from '../../shared/lib/manifest.ts';

export const manifest: FeatureManifest = {
  slug: 'inbox',
  born: '2026-08-10',
  purpose:
    "One screen aggregating everything that has ever arrived at this wallet over Nostr -- chat messages, spend requests, vault-membership invites, family/circle attestation arrivals, and safety phrases -- with category tabs, per the operator's 2026-08-10 request: \"we need an inbox ... I feel like we need one spot where all of that is.\" Every category already had a receiving surface scattered elsewhere in the app (a chat list buried in the People tab, spend-request and vault-invite banners at the top of Home, safety phrases only visible in Settings); this feature does not re-implement any of that receive/accept/decline logic, it composes the existing self-contained hooks and components into one place reachable from a header link.",
  touches: ['src/features/inbox/InboxScreen.tsx'],
  depends_on: ['wallet-core', 'transport', 'sign-request', 'circle-phrase', 'connections'],
  pause_safe: true,
  removal_safe: true,
  monetizable: false,
  notes:
    "InboxScreen.tsx is read-only aggregation, not a new data path: it calls useWallet() for inboxEnvelopes/chatThreadsByPeer (already-global state owned by WalletProvider, no new subscription), mounts its own useInboxRouting() instance (same hook HomeScreen uses, independently instantiated -- each screen owns its own modal stack), and renders the EXISTING InboxPanel and CirclePhraseSection components as-is inside category sections. The 'Messages' tab lists chatThreadsByPeer (global chat state) sorted by last-message time and links to '/?tab=people', which HomeScreen.tsx's new initialTabFromUrl() reads once on mount to land directly on the People tab where the full thread lives -- deep-linking into a SPECIFIC peer's open thread was deliberately left alone (that selection state is owned locally inside PeopleTabBody and lifting it to the URL is a bigger, separate change not needed to satisfy 'one spot to see it's there and click through'). Duplicate-subscription fix (2026-08-11, operator: \"Just received a spend request but didn't show in inbox\") -- this note used to claim the screen's own usePsbtCosignRequests/useVaultMembershipRequests calls alongside IncomingPsbtCosignBanner/IncomingVaultMembershipBanner's internal calls to the SAME hooks was intentional, \"matching the existing pattern.\" It was wrong: two fully independent subscription instances, each running its own async load-persisted-set-then-subscribe chain, could disagree about what had arrived or about which had finished subscribing yet -- the empty-state text and the actual banner could show two different realities on the same screen. Fixed in the sign-request feature (IncomingPsbtCosignBannerView / IncomingVaultMembershipBannerView, presentational components taking already-fetched state as a prop); this screen now calls each hook exactly once and passes that single state to both the empty-state check and the *View component. \"Still not showing past things\" fix, same session -- Spend requests and Vault invites never got the \"keep until you delete it\" treatment Messages and Family & circle got on 2026-08-10 (requestHistoryStore.ts, storage feature): dismiss() only ever remembered a bare key, throwing the request's content away the instant it was handled. Both hooks now also return `history` (every request ever seen, newest first) and `deleteHistoryEntry`; this screen's new local RequestHistoryList component renders the HANDLED subset (status !== 'pending' -- a still-pending item already shows in the live banner above, showing it twice would be redundant) with a Delete button per row, reusing the same non-pending filter and status-label maps for both categories.",
};
