import type { FeatureManifest } from '../../shared/lib/manifest.ts';

export const manifest: FeatureManifest = {
  slug: 'governance',
  born: '2026-05-25',
  purpose:
    'Tapscript-style authorization-tree primitives for organizations. Phase 8 Phase A and Phase B of the canonical brief (project-memory/foreman-memory/projects/tapit-wallet/briefs/2026-05-25-tapscript-style-org-authorization-tree-roadmap.md) extracted from src/features/connections/createOrganization.ts at Phase C cut-time so file-size headroom on createOrganization.ts is restored before any UI work touches it. Phase E1 (open-joining brief) extended the AuthRule type to a discriminated union of AuthRuleForOrgAction (signer-side {threshold, eligible} — issuance, expulsion, charter amendment) and AuthRuleForJoin (joiner-side {policy: JoinPolicy} where JoinPolicy is the six-kind union: open / allow_list / deny_list / requires_handshake / requires_credential / requires_vouch). Exports the discriminated union + AuthRuleForOrgAction + AuthRuleForJoin + JoinPolicy + isOrgActionRule / isJoinRule type guards + the encode/decode/build helpers for the auth sub-branch + findAuthRule + listAuthRules + proveAuthorization (the producer side of cross-envelope authorization proofs) + AuthorizedByPayload + encode/decode/buildAuthorizedByPayload + the OrgAuthorizationResult shape. Phase E3 cut 1 (this cut, hybrid substrate per the open-joining brief Option 3) ships evaluateJoinPolicy.ts — a pure function that takes a JoinPolicy, an incoming self-membership envelope, and the org wallet\'s current holdings, and returns {accepted, reason}. Three list-checking kinds (open / allow_list / deny_list) accept or reject purely from the envelope\'s joiner pubkey; the three proof-requiring kinds (requires_handshake / requires_credential / requires_vouch) reject with a reason naming Phase E4 as the milestone that adds joiner-side proof attachment + reading. The verifier itself (verifyOrgAuthorization) stays in connections/createOrganization.ts because it uses the org-self-declaration predicate; everything else is org-agnostic substrate that future cuts (Phase E3 cut 2 pending-roster buffer + roster-publication envelope, Phase E4 verifier-side proof reading + UI; Phase D charter amendment) extend in place.',
  touches: [
    'src/features/governance/authRule.ts',
    'src/features/governance/authRule.test.ts',
    'src/features/governance/evaluateJoinPolicy.ts',
    'src/features/governance/evaluateJoinPolicy.test.ts',
  ],
  depends_on: ['wallet-core'],
  pause_safe: false,
  removal_safe: false,
  monetizable: false,
  notes:
    'Zero new cryptographic code; the entire module is a layer over the shipped disclosureProof / verifyDisclosureProof primitive from tapit-attest/src/core/field-tree.ts, applied to AUTHORIZATION RULES instead of facts. The substrate this module ships is what Phase C UI (multi-rule org creation form), Phase D (charter amendment chain), and Phase E1+ (open-joining via a discriminated-union join-rule kind) all build on top of without further substrate work. Phase B verifier (verifyOrgAuthorization) intentionally stays in connections/createOrganization.ts because it filters knownOrgs via isOrganizationSelfDeclaration which is org-specific; the verifier imports the rule-decoding and payload-decoding primitives from this module. Tests for the data-model layer live in authRule.test.ts alongside the code (each JoinPolicy kind round-trips encode → decode unchanged; buildAuthSubtree validates kind-specific constraints; type guards are exercised). Tests for the org-specific glue (verifyOrgAuthorization, createMembership integration) live in createOrganization.test.ts / createMembership.test.ts where they exercise the producer-verifier loop end-to-end. Phase E1 dispatch is by action name: a leaf whose name is "join" decodes via the join-policy path; any other leaf name decodes via the {threshold, eligible} path, preserving backward compatibility with pre-E1 declarations whose canonical-JSON shape is unchanged.',
};
