import type { FeatureManifest } from '../../shared/lib/manifest.ts';

export const manifest: FeatureManifest = {
  slug: 'journal',
  born: '2026-05-21',
  purpose:
    'The diary wedge. Composer for signed journal-kind attestations with a subject picker (Me / Someone-else label), a category picker (Diary / Family / Medical / Marriage / Witness plus free-form), free-text entry, optional attachment (photo via camera shortcut or document via file picker — PDF, text, Word, Excel, etc.). Each entry is signed by the wallet, queued for OpenTimestamps anchoring, and renders as a card on the home screen grouped by category tab. Detail view per entry shows the attachment (image inline, document as a download link) and exposes a save-to-files download.',
  touches: [
    'src/features/journal/JournalComposer.tsx',
    'src/features/journal/JournalCard.tsx',
    'src/features/journal/JournalDetail.tsx',
    'src/features/journal/JournalTabs.tsx',
    'src/features/journal/JournalTabRouter.tsx',
    'src/features/journal/FreshTodayCarousel.tsx',
    'src/features/journal/FreshTodayCard.tsx',
    'src/features/journal/FreshComposeFAB.tsx',
    'src/features/journal/FreshMemoriesStrip.tsx',
    'src/features/journal/FreshStreakIndicator.tsx',
    'src/features/journal/useScrollDirection.ts',
    'src/features/journal/findMemoryEntries.ts',
    'src/features/journal/computeStreak.ts',
    'src/features/journal/createJournalEntry.ts',
    'src/features/journal/downloadEntry.ts',
    'src/features/journal/categories.ts',
    'src/features/journal/categoryAccents.ts',
    'src/features/journal/normalizeImage.ts',
    'src/features/journal/verifyAttachmentIntegrity.ts',
    'src/features/journal/stampPhoto.ts',
    'src/features/journal/StampedPhotoButton.tsx',
    'src/features/journal/momentDate.ts',
    'src/features/journal/journalTags.ts',
    'src/features/journal/journalTags.test.ts',
  ],
  depends_on: ['wallet-core', 'storage', 'anchoring', 'theme', 'connections', 'disclosure', 'qr', 'camera'],
  pause_safe: false,
  removal_safe: false,
  monetizable: false,
  notes:
    'Subject is a typed label so the grandchild-from-birth scenario works without a child wallet existing. A custody handoff (Phase 2.6+) is a meta-kind attestation signed by old + new custodian. Each entry is held by the wallet and persisted via the storage layer the same way the identity attestation is. In-app camera 2026-06-05 ("let\'s build a camera"): the composer now has a 📷 Camera button that opens the reusable CameraCaptureModal (src/features/camera) — a live getUserMedia preview with front/back toggle + shutter, degrading to the native capture input on installed iOS PWA / unsupported / error. The captured JPEG flows through onPickAttachment -> normalizeImage -> sign -> anchor -> stamp exactly like a picked file, so "take it through the app and it stamps it" is now literal. The old library picker stays as the 🖼 Photo button; 📄 Document unchanged. depends_on gained camera. Stamped-photo cut 2026-06-05 (operator: "have the metadata lock up in the corner of the picture... a selfie or you take it through the app it automatically stamps it or put it on there later"): the operator chose "stamped copy on share" in chip form — the signed + anchored original is NEVER modified (keeps file-integrity simple and the digest well-defined), and instead StampedPhotoButton composites a verification badge onto a COPY when sharing. stampPhoto.ts draws onto a canvas from the displayed image and burns a corner panel carrying a Tapit mark + capture date + who captured it + the Bitcoin block (once confirmed) + a scannable QR, then returns a fresh JPEG. The QR resolves to /verify with a multiDisclosureProof bundle disclosing the attachment_sha256 leaf (+ written_at) built via disclosure/buildVerifyUrl.ts (extracted from QuickShareModal so both build the same one-tap link); a scanner re-hashes the photo to confirm it is the signed-and-anchored one. qrcode is dynamically imported inside stampPhoto so it only loads on demand. Sharing uses shared/lib/share.ts shareFile (Web Share API Level 2 files pathway → system sheet incl. AirDrop/Save-to-Files, with a download fallback on engines without file-sharing). The badge can show the live block because it is rendered at share time, not baked at capture — the deliberate consequence of the stamped-copy model. depends_on gained connections (displayNameOf for the captured-by line), disclosure (buildVerifyUrl), and qr (the qrcode lib path). Moments cut 2026-06-14 (family-nest build plan, first visible cut): the composer gained an optional "When did this happen?" date input that writes an honestly-marked event_date leaf, kept deliberately separate from written_at (which is ALWAYS now and never forged). This is the keystone primitive for the sovereign-family-nest thesis — it lets an older memory be backfilled (the 25-year-old ball game, a photographed keepsake card, an elder\'s story about a long-ago year) without ever lying about when it was recorded: the signature + anchor prove "this existed unchanged by the day it was logged" while event_date is an honest claim "and it is about this earlier day." The pure helpers live in momentDate.ts (readEventDate / readWrittenAt / momentTimestamp / isBackfilled / normalizeEventDateInput which rejects future dates / formatEventDate which avoids the UTC-midnight off-by-one on date-only strings), unit-tested in momentDate.test.ts. JournalDetail shows "Happened on <day>" with a "Recorded <timestamp>" line when the moment was backfilled. findMemoryEntries switched its anniversary axis from written_at to momentTimestamp so a backfilled memory resurfaces on the day it actually happened; entries without an event_date match on written_at exactly as before. See briefs/2026-06-14-ultimate-cut-list-and-clear-vision.md. Diary tags (2026-06-16, operator: "tag pictures/diary with categories — food, pictures, places, friends — and pull them back up by tag, plus custom"): journalTags.ts (pure + tested) holds SUGGESTED_TAGS (Food/Places/Friends/Family/Things/Pictures/Travel/Work/Health/Pets/Nature/Fun/Faith/Money/Learning/Milestone) + readTags / normalizeTag / dedupeTags / hasTag / allTags(count) / entriesWithTags (AND filter). Tags are a SEPARATE multi-value signed `tags` leaf (canonical JSON array, deduped) distinct from the single `category` tab — createJournalEntry writes it. JournalComposer gained a multi-select suggested-tag chip strip + a custom-tag input (type + Enter/Add); both Classic JournalTabs and Fresh FreshTodayCarousel gained a tag-filter chip strip (tap to AND-narrow, with per-tag counts + clear) so entries pull back up by tag; JournalDetail shows an entry\'s tags. Composer is shared so tagging works in both themes.',
};
