import type { FeatureManifest } from '../../shared/lib/manifest.ts';

export const manifest: FeatureManifest = {
  slug: 'recovery',
  born: '2026-05-24',
  purpose:
    'Phase 5e — hyphal lattice + Shamir cascade recovery (MYCELIUM_NETWORK_SPEC §12). Cut 5e-iii-a ships this: the operator declares which peers from their handshake web they would trust to help recover this wallet on a new device, along with the (M, N) threshold the recovery ceremony will require. The cohort is recorded as a self-signed credential, anchored to Bitcoin alongside everything else. Share distribution + backup-format v2 lands in 5e-iii-b. The recovery ceremony itself (initiator + responder + recovery-succession event) lands in 5e-v / -vi / -vii. The cryptographic floor (GF(256) Shamir split + combine) shipped in tapit-attest at 5e-ii. The load-bearing constraint stays loud: the Shamir split is over the backup ENCRYPTION KEY, never the signing keypair.',
  touches: [
    'src/features/recovery/createCohort.ts',
    'src/features/recovery/createCohort.test.ts',
    'src/features/recovery/CohortEditorModal.tsx',
    'src/features/recovery/lattice.ts',
    'src/features/recovery/LatticePanel.tsx',
    'src/features/recovery/createShares.ts',
    'src/features/recovery/createShares.test.ts',
    'src/features/recovery/DistributeSharesModal.tsx',
    'src/features/recovery/createRecoveryRequest.ts',
    'src/features/recovery/createRecoveryRequest.test.ts',
    'src/features/recovery/RecoveryResponderModal.tsx',
    'src/features/recovery/RecoveryInitiatorModal.tsx',
    'src/features/recovery/RecoveryConfigStep.tsx',
    'src/features/recovery/RecoveryAwaitingShares.tsx',
    'src/features/recovery/RecoveryNamingStep.tsx',
    'src/features/recovery/recoveryInitiatorTypes.ts',
    'src/features/recovery/RecoveryKeyImportModal.tsx',
    'src/features/recovery/RestoreFromFileModal.tsx',
    'src/features/recovery/createRecoverySuccession.ts',
    'src/features/recovery/createRecoverySuccession.test.ts',
    'src/features/recovery/sharedSecret.ts',
    'src/features/recovery/sharedSecret.test.ts',
    'src/features/recovery/SharedSecretModal.tsx',
    'src/features/recovery/SharedSecretSection.tsx',
  ],
  depends_on: ['wallet-core', 'anchoring', 'connections', 'qr'],
  pause_safe: true,
  removal_safe: true,
  monetizable: false,
  notes:
    'RecoveryInitiatorModal extraction 2026-05-28 (PLAN.md Tier 1 item 2): the three phase-render blocks (configuring → RecoveryConfigStep, sending/awaiting/combining/restoring → RecoveryAwaitingShares, naming → RecoveryNamingStep) plus shared types + helpers (recoveryInitiatorTypes) moved into sibling files so the orchestrator stays under the 800-line hard limit. Sub-components own presentation only; the absorb-share / publish-result / combine-and-restore / save-under-new-passphrase logic stays in the parent. Done pre-emptively before the Tier 1 cross-device recovery field-test so any fixes that test surfaces land in the right sub-component rather than re-growing the orchestrator. The cohort credential carries the member list as canonical JSON of {pubkey, name} pairs sorted + deduplicated so the digest is stable regardless of pick order. Latest-by-issuedAt wins for the in-effect cohort; older cohorts stay held + anchored for governance audit. Cohort members are sourced from existing handshakes today; organizations from memberships are a follow-on (would extend candidate pool from isMembership holdings). The publishCohort builder validates threshold + totalShares + member count + Shamir GF(256) ceiling (255 max) before signing. Family safe-word cut 2026-06-03: sharedSecret.ts reuses the same chassis Shamir split/combine the cohort uses but points it at an arbitrary secret STRING instead of the backup key — a self-contained, wallet-independent tool (split a word M-of-N, hand out the encoded pieces, any M paste back to rebuild). A fixed magic marker is prefixed before splitting so combining a wrong or insufficient set fails loudly rather than returning Shamir garbage that looks recovered. SharedSecretModal is the create/recover UI, SharedSecretSection is the launcher card mounted in IdentityGateSections (the "your people" grouping). Seamless-nostr cut 2026-06-04 ("make it more seamless and nostr"): each made piece can be sent straight to a person in the operator circle over the existing NIP-17 chat transport via sendChatMessage — the piece lands privately in that holder\'s Tapit wallet as a plain encrypted DM. Deliberately the LIGHTEST nostr option of the three offered (operator chose "DM pieces as chat"): the piece is a chat message, NOT a held/anchored recovery-share attestation, so there is no ceremony, no envelope kind, no inbox routing, and no permanent record on the holder side. The circle picker reuses findVouchingCircleCandidates (family/cohort/handshake); the per-piece "Send" affordance only appears when the Mycelium network is on (relayStatus !== null) and the operator has at least one connection. Rebuild stays the manual paste-back flow; Copy + QR remain the fallback for non-Tapit holders. This pulled useWallet + the circle-finder into the lazy modal chunk (budget bumped 3.5KB -> 5KB, audited). depends_on still adds nothing because the safe-word holds no wallet state of its own; it sits in recovery because it is the same Shamir substrate.',
};
